Лабароторная работа
stepancar-web-programming/2023-fall-lab-portfolio-koropchenko-a.-a. pull request #1
Opened 2023-12-20 17:09 UTC by Anatoly-Ko

2023-12-20 17:39 UTC, stepancar commented on main.css
> +#container {
обратите внимание, контейнер - не очень хорошее имя для уникального элемента. Попробуйте выбрать имя которое более точно описывает ответственность элемента. Или может такой элемент не уникален в вашем приложении? Тогда может ему не нужен id?

2023-12-20 17:41 UTC, stepancar commented on main.html
> +        let enableNight = () => {
связывание идентификатора enableNight происходит один раз, если вы ожидаете что связывание с другим значением в вашей программе не произойдет - лучше использовать const

2023-12-20 21:00 UTC, stepancar commented on main.html
> +<body id="body" class="theme--dark">
Пожалуйста, приведите код к одному виду. Например тут именование классов сделано через --, несколькими строками ниже -

2023-12-20 21:01 UTC, stepancar commented on main.html
> +                <form action="addition.html" ><button class="more">Больше</button></form>
Пожалуйста, форматируйте ваш код перед отправкой на ревью

2023-12-20 21:19 UTC, stepancar requested changes
Оставил комментарии, жду ссылку на задеплоеную демку

2024-01-04 04:11 UTC, stepancar requested changes
Обратите внимание как ваш сайт ведет себя на странице https://anatoly-ko.github.io/Anatoly/addition.html?

Попробуйте открыть в мобильном браузере , текст там не влезает. На широком экране текст не отцентрован.

2024-01-17 18:08 UTC, Anatoly-Ko commented
Добавил изменения

2024-01-19 06:19 UTC, stepancar commented on addition.html
> +    }, 10000)
Что если к моменту когда запуститься callback - узел уже будет удален?

2024-01-19 06:23 UTC, stepancar commented on main.css
> +    height: 150px;
Обратите внимание, такие стили сжимают вашу картинку. Конкретно на вашей фотографии это возможно не заметно глазу - попробуйте вставить туда фотографию с другим соотношением и вы увидите.

2024-01-19 06:31 UTC, stepancar commented on main.css
> +    -ms-flex-pack: center;
можете прислать ссылки на свойства  с вендор префиксов которые вы тут используете. Пока пытаюсь понять где вы это нашли, потому как часть из этих свойств невероятная древность, часть я просто никогда не встречал. Покажите как именно вы тестировали на всех браузерах, которые вы покрыли

2024-01-19 06:38 UTC, stepancar commented on main.html
> +                <i class="fa-solid fa-moon"></i>
Не хватает иконки солнца

2024-01-19 06:39 UTC, stepancar commented on main.html
> +            <label for="night" class="night-mode" onclick="enableNight()">
Обратите внимание, несмотря на то, что это контрол, на него нельзя навигироваться с клавиатуры. Давайте это исправим

2024-01-19 06:40 UTC, stepancar commented on style.css
> +    max-height: 100vh;
обязательно проверьте корректность работы на iphone так как в safari ios 100vh уже много лет работает некорректно

2024-01-19 06:41 UTC, stepancar commented on style.css
> +
```suggestion
```

2024-01-19 06:41 UTC, stepancar commented on main.html
> +            var body = document.getElementById("body");
```suggestion
            const body = document.getElementById("body");
```

2024-01-19 06:45 UTC, stepancar commented
<img width="1131" alt="Screenshot 2024-01-18 at 10 44 59 PM" src="https://github.com/stepancar-web-programming/2023-fall-lab-portfolio-koropchenko-a.-a./assets/2854910/cdae4314-e900-4faa-acb4-8459c5880e88">

Пока на телефоне выглядит средне

2024-01-19 06:45 UTC, stepancar requested changes
Оставил замечания

2024-01-19 18:46 UTC, Anatoly-Ko commented on main.css
> +    -ms-flex-pack: center;
Я уже точно не помню, скорее всего где-то на ютубе. Вот как пример ссылка, здесь перечислены все использованные мной: http://blogo-daru.ru/2017/04/09/prefiksy-dlya-flexbox-css-krosbrauzernyj-flexbox/
Тестировал в chrome и safari со своего компьютера, все работало.

2024-01-19 18:46 UTC, Anatoly-Ko commented on main.html
> +                <i class="fa-solid fa-moon"></i>
Добавил

2024-01-19 18:47 UTC, Anatoly-Ko commented on main.html
> +            <label for="night" class="night-mode" onclick="enableNight()">
Добавил. Теперь переключение между кнопками происходит с помощью tab, нажатие - enter.

2024-01-19 18:49 UTC, Anatoly-Ko commented on style.css
> +    max-height: 100vh;
Запускал на своем iPhone, все работает.

2024-01-19 18:50 UTC, Anatoly-Ko commented
Все исправил. 
Очень-очень не хочется на допсу :(

2024-01-20 02:11 UTC, stepancar commented on main.css
> +    -ms-flex-pack: center;
@Anatoly-Ko , данная статья 2017 года, начинается со слов 

```
В момент написания заметки поддержка flexbox браузерами составляет 86,3% без использования префиксов и 97,7% с ними.
```

Давайте разберемся с поддержкой свойств, которые вы используете. Точно ли префиксы которые вы использовали имеют смысл в 2023/2024 году? Для этого вы можете воспользоваться [can I use ](https://caniuse.com/)

2024-01-20 02:13 UTC, stepancar commented on main.html
> +                <i class="fa-solid fa-moon"></i>
При первом нажатии на иконка не меняется 

https://github.com/stepancar-web-programming/2023-fall-lab-portfolio-koropchenko-a.-a./assets/2854910/d263a85e-e6b6-4799-942c-e2bb65837205

2024-01-20 02:20 UTC, stepancar commented on style.css
> +      }
Вы не используете автоматические средства для форматирования, линтинга вашего проекта.
Прошу добавить интеграцию с линтерами, плюс к уже сделанному в вашем проекте, чтобы закрепить

2024-01-20 02:21 UTC, stepancar requested changes
Оставил замечания

2024-01-20 13:14 UTC, Anatoly-Ko commented on style.css
> +      }
Добавил esLint и prettier

2024-01-20 13:14 UTC, Anatoly-Ko commented on main.html
> +                <i class="fa-solid fa-moon"></i>
исправлено

2024-01-20 13:15 UTC, Anatoly-Ko commented on main.css
> +    -ms-flex-pack: center;
Проверил на сайте, не поддерживаемые убрал. Спасибо, сохранил сайт в закладках)

2024-01-21 03:55 UTC, Anatoly-Ko commented
Посмотрите, пожалуйста

2024-01-21 19:00 UTC, stepancar requested changes
в PR закоммичены node_modules. Это значит, что перед отправкой на ревью вы не посмотрели на ПР и не убедились в его чистоте
<img width="1001" alt="Screenshot 2024-01-21 at 11 00 43 AM" src="https://github.com/stepancar-web-programming/2023-fall-lab-portfolio-koropchenko-a.-a./assets/2854910/f2d8bd7d-cbf7-4c19-9602-e26b65a5f0eb">

2024-01-21 19:10 UTC, Anatoly-Ko commented
убрал лишнее

2024-01-21 20:42 UTC, stepancar commented on package.json
> +    "eslint-plugin-import": "^2.29.1"
это devDependencies, согласны?
Напоминаю, в рубежке есть вопрос про это

2024-01-21 21:05 UTC, stepancar commented on .eslintrc
> +    "extend": "airbnb-base"
я так понимаю, https://www.npmjs.com/package/eslint-config-airbnb-base ? но не вижу его у вас в devDependencies

2024-01-21 21:11 UTC, stepancar requested changes
Объясню подробнее, почему у нас с вами возникают сложности по вашей лабораторной. Обратитве внимание что на данный момент мы обсуждаем вопросы не сколько frontend разработки, а в целом разработки.

 Выкачаваю я ваш проект. Переключаюсь в ветку dev как сказано в задании
Не нахожу инструкцию как запустить. Если инструкции нету то разработчик обычно анализирует на каком стеке технологий сделан проект.
Я понимаю, что в проекте есть package.json , догадываюсь о том что это node package.json.

Открываю его - хочу выполнить команды из секции scripts , а их нет.
При этом в ПР написано что вы добавили линтинг. В итоге, по видимому в проекте есть линтинг, но помните о том как его запустить только вы.
В вопросах РК1 есть вопрос про структуру package.json . Там есть специальная секция scripts. На занятиях мы говорили как важно предоставить их разработчикам чтобы они могла просто запустить одну команду
Если вы пишете не фронтэнд проект, скорее всего вы добавляете makefile чтобы другие могли запустить, правда ведь?

Хорошо. я устанавливаю зависимости. Сразу получаю diff git в 5000 файлов node_moduels. У нас выше есть дискуссия о том что в ПР 5000 файлов. Вы случайно закоммитили, потом удалили, но саму проблему не решили.
Для решения этой проблемы используется gitignore.

Установив зависимости я так же вижу что появился новый файл package-lock.json
Мы обсуждали это на парах, так же про npm есть вопрос в рубежке.  Этот файл должен быть закоммичен, чтобы обеспечить идентичность зависимостей у всех разработчиков. обратите внимание на содержимое этого файла
Но даже если об этом не знать/не помнить - когда вы скачиваете проект, запускаете его, устанавливаете зависимости - это не должно приводить к добавлению каких-то файлов в гите просто так.

Далее, я решаю, хорошо, я не разобрался как запустить линтеры. 
Но я тогда могу пойти и посмотреть логи на CI и убедиться что все хорошо. А логов нет и CI нет. в итоге если я сейчас закоммичу ПР - я могу испортить ваш проект, не смотря на то, что есть линтеры.

Далее - вы пишите, добавили prettier. а в зависимостях его нет, все так же не понятно как его запустить

Далее, вы пишите, что вы удалили префиксы для старых браузеров. 
https://github.com/stepancar-web-programming/2023-fall-lab-portfolio-koropchenko-a.-a./pull/1#discussion_r1460434810
Я захожу на ваш сайт, смотрю файлы, которые скачаны.
Вижу там ничего не исправлено.

<img width="1666" alt="Screenshot 2024-01-21 at 1 13 43 PM" src="https://github.com/stepancar-web-programming/2023-fall-lab-portfolio-koropchenko-a.-a./assets/2854910/d850e7f4-6139-4f76-b736-2dce8217be40">

Вероятно, вы забыли сделать деплой. Это как раз подчеркивает проблему отсутствие автоматизации в вашем проекте. Представьте цену такой проблемы. Вы с коллегами исправляете некий серьезный баг. все закоммитили, но на продакшен забыли сделать деплой.

2024-01-21 22:00 UTC, Anatoly-Ko commented
Привел в порядок линтер

2024-01-21 22:04 UTC, Anatoly-Ko commented
По поводу автоматизации выгрузки страницы. Да тут я полностью с Вами согласен, но все же прошу простить мне данную огреху в визитке, иначе у меня точно не останется шансов попасть на экзамен. Я обязательно это учту и продемонстрирую большую автоматизацию в групповом проекте. Согласитесь Вы на такой вариант?

2024-01-21 22:18 UTC, stepancar commented on main.html
> +            <img src="photo.jpeg" alt="" class="pic">
ccылка на фото есть, самого фото в репозитории нет

2024-01-21 22:20 UTC, stepancar commented on .gitignore
> +package-lock.json
Пожалуйста, убедитесь что вы понимаете назначение этого файла.

2024-01-21 22:23 UTC, Anatoly-Ko commented
Добавил фото и видео.

2024-01-21 22:25 UTC, Anatoly-Ko commented on .gitignore
> +package-lock.json
Данный файл - .gitignore позволяет не выгружать файлы, содержащиеся в проекте, в гитхаб.

2024-01-21 22:32 UTC, stepancar commented on .gitignore
> +package-lock.json
@Anatoly-Ko , я указал ведь на конкретную строку в этом комментарии, на файл package-lock.json

2024-01-21 22:36 UTC, stepancar commented on style.css
> +      }
Не вижу prettier в зависимостях

2024-01-21 22:36 UTC, Anatoly-Ko commented on .gitignore
> +package-lock.json
Данный файла создается npmом, хранит зависимости и их версии.

2024-01-21 22:38 UTC, stepancar commented on .gitignore
> +package-lock.json
@Anatoly-Ko , какое у него назначение и почему некорректно этот файл игнорировать, а корректно добавлять в git?

2024-01-21 22:40 UTC, stepancar commented on package.json
> +    "eslint-config-airbnb": "^19.0.4"
Вы торопитесь и делаете чисто механическую работу. 
В этом комментарии, я указал вам на проблему.
https://github.com/stepancar-web-programming/2023-fall-lab-portfolio-koropchenko-a.-a./pull/1#discussion_r1461113082
Вы исправили проблему для одной зависимости и не пошли дальше

2024-01-21 22:43 UTC, Anatoly-Ko commented on package.json
> +    "eslint-config-airbnb": "^19.0.4"
У меня prettier используется просто как расширение для VS Code. Я его не подгружал.

2024-01-21 22:46 UTC, Anatoly-Ko commented on .gitignore
> +package-lock.json
Корректно добавлять, поскольку он обеспечивает идентичную установку зависимостей в различных окружениях. Также его назначение - безопасность (версии пакетов) и оптимизация (установка зависимостей).

2024-01-21 22:47 UTC, stepancar commented
> По поводу автоматизации выгрузки страницы. Да тут я полностью с Вами согласен, но все же прошу простить мне данную огреху в визитке, иначе у меня точно не останется шансов попасть на экзамен. Я обязательно это учту и продемонстрирую большую автоматизацию в групповом проекте. Согласитесь Вы на такой вариант?

Хорошо, автоматический деплой на https://anatoly-ko.github.io/Anatoly/ из этого репозитория можете не делать.
Но я не понимаю причины не сделать просто автоматический деплой в этом репощ=з, потому что автоматический деплой для статичного контента из ветки работает без каких-либо усилий.

https://stepancar-web-programming.github.io/2023-fall-lab-portfolio-koropchenko-a.-a./main.html
Вы уже научилисль публиковать код из ветки, судя по демо, которое вы мне прислали на проверку. https://anatoly-ko.github.io/Anatoly/
Но видимо вы не разобрались до конца в мануале, по которому вы это делали.

Ваш сайт доступен по адресу https://stepancar-web-programming.github.io/2023-fall-lab-portfolio-koropchenko-a.-a./main.html
И его контент меняется на каждый коммит

2024-01-21 22:49 UTC, Anatoly-Ko commented
> > По поводу автоматизации выгрузки страницы. Да тут я полностью с Вами согласен, но все же прошу простить мне данную огреху в визитке, иначе у меня точно не останется шансов попасть на экзамен. Я обязательно это учту и продемонстрирую большую автоматизацию в групповом проекте. Согласитесь Вы на такой вариант?
> 
> Хорошо, автоматический деплой на https://anatoly-ko.github.io/Anatoly/ из этого репозитория можете не делать. Но я не понимаю причины не сделать просто автоматический деплой в этом репозитория, потому что автоматический деплой для статичного контента из ветки работает без каких-либо усилий.
> 
> https://stepancar-web-programming.github.io/2023-fall-lab-portfolio-koropchenko-a.-a./main.html Вы уже научилисль публиковать код из ветки, судя по демо, которое вы мне прислали на проверку. https://anatoly-ko.github.io/Anatoly/ Но видимо вы не разобрались до конца в мануале, по которому вы это делали.
> 
> Ваш сайт доступен по адресу https://stepancar-web-programming.github.io/2023-fall-lab-portfolio-koropchenko-a.-a./main.html И его контент меняется на каждый коммит

Я не мог получить доступ к pages из данного репозитория, поскольку у меня не было администраторских прав. Теперь действительно, все будет автоматизированного. Всегда выгружаю изменения исключительно через терминал в vs Code, а не вручную. Сейчас обновлю ссылку в Readme, спасибо.

2024-01-21 22:51 UTC, stepancar commented on package.json
> +    "eslint-config-airbnb": "^19.0.4"
@Anatoly-Ko , не понимаю ваш комментарий. В этот треде вопрос не про prettier, а про deps/ devDeps

2024-01-21 22:55 UTC, stepancar commented on main.css
> +    -ms-flex-align: center;
В рамках дискуссии мы выяснили что браузеры, которые вы пытаетесь поддержать устарели.
Вы с этим согласились. однако в коде я так же вижи префиксы
https://github.com/stepancar-web-programming/2023-fall-lab-portfolio-koropchenko-a.-a./pull/1#discussion_r1460434810

2024-01-21 22:59 UTC, Anatoly-Ko commented on package.json
> +    "eslint-config-airbnb": "^19.0.4"
Согласен, глупая ошибка. Убрал дублирующую строку

2024-01-21 23:01 UTC, Anatoly-Ko commented on main.css
> +    -ms-flex-align: center;
Я убрал только те, которые абсолютно не поддерживаются, исходя из данных сайта can i use. Как пример:
![Uploading Снимок 22.01.2024 в 02.00.jpeg…]()

2024-01-21 23:02 UTC, Anatoly-Ko commented on main.css
> +    -ms-flex-align: center;
![Снимок 22 01 2024 в 02 00](https://github.com/stepancar-web-programming/2023-fall-lab-portfolio-koropchenko-a.-a./assets/54147638/bc8bc38c-4440-4be7-97b3-51f2be4b9f4f)

2024-01-22 03:29 UTC, stepancar commented on .gitignore
> +package-lock.json
жду добавление

2024-01-22 03:33 UTC, stepancar commented on main.css
> +    -ms-flex-align: center;
@Anatoly-Ko обратите внимание, что написано внизу страницы
<img width="649" alt="Screenshot 2024-01-21 at 7 32 14 PM" src="https://github.com/stepancar-web-programming/2023-fall-lab-portfolio-koropchenko-a.-a./assets/2854910/40fd7779-7656-40ea-88f4-882776a527a7">

2024-01-22 03:38 UTC, stepancar commented on main.css
> +    -ms-flex-align: center;
@Anatoly-Ko , если вы сделаете автоматизацию, нам не придется вести эту дискуссию бесконечно 😃 
Вот часть ошибок, которые находит линтер стилей https://stylelint.io/

<img width="1067" alt="Screenshot 2024-01-21 at 7 36 50 PM" src="https://github.com/stepancar-web-programming/2023-fall-lab-portfolio-koropchenko-a.-a./assets/2854910/01f60950-0dc0-4737-9111-b394b3076069">

2024-01-22 05:02 UTC, stepancar commented on package.json
> +  },
Обратите внимание на то, что у вас есть файл eslintrc.js где написано то же самое. для чего вам эта настройка в package.json?

2024-01-22 08:29 UTC, Anatoly-Ko commented
Внёс изменения

2024-01-22 13:15 UTC, stepancar commented on stylelint.config.js
> +      ],
Тут

2024-01-22 20:52 UTC, stepancar approved these changes

2024-01-22 20:52 UTC, merged